name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install and Run Tests
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          # Ensure pytest and requests are either in requirements.txt or explicitly installed
          pip install -r requirements.txt
          # If pytest isn't in requirements.txt, add this line:
          # pip install pytest requests
          pytest --maxfail=1 --disable-warnings -v
